# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target '动动' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 动动
  pod 'Masonry'
  pod 'AFNetworking'
  pod 'YYKit'
  pod 'BlocksKit'
  pod 'MBProgressHUD'
  pod 'MJRefresh'
  pod 'UITableView+FDTemplateLayoutCell'
  pod 'iCarousel'
  pod 'WMPageController'
  pod 'MWPhotoBrowser'

end
